title: "dev>mode13h"
description: ~ night-time gamedev & geek ~

author: # Author details
  username: root
  name: Marco Lizza
  url: https://mode13h.dev
  copyright: "&copy; Copyright 2014-2025"

social:
  bluesky: mode13h.dev
  github: MarcoLizza
  mastodon:
  itchio: mode13h
  discord:
  linkedin:

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title/

include:
  - _pages

exclude:
  - CNAME
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .sass-cache

plugins_dir:
  - jekyll-tidy

jekyll_tidy:
  compress_html: false

# Terminal theme settings
prompt: "[reader@mode13h.dev ~]$"
recent_posts_limit: 16
