# Site settings
title: "mode13h"
logo_url: "/assets/images/logo.png"
email: marco.lizza@gmail.com
description: ~ night-time gamedev & geek ~
url: "" # the base hostname & protocol for your site
#url: "http://localhost:4000" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

author: # Author details
  name: Marco Lizza
  email: marco.lizza@gmail.com
  url: https://mode13h.io
  copyright: "&copy; Copyright 2014-2022 by Marco Lizza"

# Profile links, leave blank to ignore
social: 
  twitter: MarcoLizza
  github: MarcoLizza
  mastodon: mastodon.gamedev.place/@mode13h
  itchio: mode13h 
  discord: 665298248541667367/665298858263445504
  linkedin: marco-lizza

# Google Analytics key, leave blank to ignore
google:
  analytics_id: UA-131188350-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title/

include:
  - _pages

exclude:
  - CNAME
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .sass-cache

sass:
  sass_dir: assets/css/_sass
  style: :compressed

plugins_dir:
  - jekyll-tidy

jekyll_tidy:
  compress_html: false
